#Сообщения
usage: "&fИспользование: &6/targetcompass x, z"
nocompass: "&cУ вас в руке должен находится компас"
set-error: "&cГраницы этого мира не позволяют установить такие координаты"
set-success: "&fУра! Теперь ваш компас показывает на координаты &6x: %x, z: %z"

#Ограничение установки координат и миров

worlds:
  world:
    x1: 4500
    x2: -4500
    z1: 4500
    z2: -4500
  spawn:
    x1: 200
    x2: -200
    z1: 200
    z2: -200
  world_nether:
    x1: 4500
    x2: -4500
    z1: 4500
    z2: -4500
  world_the_end:
    x1: 4500
    x2: -4500
    z1: 4500
    z2: -4500