#Сообщения
usage: "&fИспользование: &6/targetcompass x, z"
nocompass: "&cУ вас в руке должен находится компас"
block-world: "&cНельзя это делать в мирах, кроме world"
set-error: "&cНельзя устанавливать координаты больше -4500 или 4500"
set-success: "&fУра! Теперь ваш компас показывает на координаты &6x: %x, z: %z"

#Ограничение установки координат
x1: 4500
x2: -4500
z1: 4500
z2: -4500